export const ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  DUPLICATE_REGISTRATION: "DUPLICATE_REGISTRATION",
  INVALID_STATE_TRANSITION: "INVALID_STATE_TRANSITION",
  TICKET_ALREADY_ISSUED: "TICKET_ALREADY_ISSUED",
  TICKET_ALREADY_CHECKED_IN: "TICKET_ALREADY_CHECKED_IN",
  TICKET_REVOKED: "TICKET_REVOKED",
  EVENT_NOT_LIVE: "EVENT_NOT_LIVE",
  EVENT_NOT_ACCEPTING: "EVENT_NOT_ACCEPTING",
  VERIFIER_EXPIRED: "VERIFIER_EXPIRED",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const HTTP_STATUS_MAP: Record<ErrorCode, number> = {
  [ERROR_CODES.UNAUTHORIZED]: 401,
  [ERROR_CODES.FORBIDDEN]: 403,
  [ERROR_CODES.NOT_FOUND]: 404,
  [ERROR_CODES.VALIDATION_ERROR]: 400,
  [ERROR_CODES.DUPLICATE_REGISTRATION]: 409,
  [ERROR_CODES.INVALID_STATE_TRANSITION]: 400,
  [ERROR_CODES.TICKET_ALREADY_ISSUED]: 409,
  [ERROR_CODES.TICKET_ALREADY_CHECKED_IN]: 409,
  [ERROR_CODES.TICKET_REVOKED]: 400,
  [ERROR_CODES.EVENT_NOT_LIVE]: 400,
  [ERROR_CODES.EVENT_NOT_ACCEPTING]: 400,
  [ERROR_CODES.VERIFIER_EXPIRED]: 401,
  [ERROR_CODES.RATE_LIMITED]: 429,
  [ERROR_CODES.INTERNAL_ERROR]: 500,
};
